//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Data_User_Activity_Log
{
    public int id { get; set; }
    public string username { get; set; }
    public string pageUrl { get; set; }
    public string activity { get; set; }
    public Nullable<System.DateTime> dateCreated { get; set; }
}

public partial class Data_Workplan
{
    public int id { get; set; }
    public Nullable<System.DateTime> call_date { get; set; }
    public Nullable<int> branch_id { get; set; }
    public Nullable<int> is_deleted { get; set; }
    public Nullable<int> user_id { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public Nullable<System.DateTime> date_submitted { get; set; }
    public Nullable<System.DateTime> deadline { get; set; }
    public Nullable<int> added_by { get; set; }
    public string reference { get; set; }
    public Nullable<System.DateTime> viewed_at { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }
    public Nullable<int> modified_by { get; set; }
}

public partial class Ref_User
{
    public int id { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string fullname { get; set; }
    public string firstname { get; set; }
    public string middle { get; set; }
    public string lastname { get; set; }
    public string type { get; set; }
    public string area { get; set; }
    public Nullable<double> is_active { get; set; }
    public string email { get; set; }
    public string agency { get; set; }
    public Nullable<int> team_leader { get; set; }
}

public partial class vw_data_workplan_tl
{
    public int id { get; set; }
    public Nullable<System.DateTime> call_date { get; set; }
    public Nullable<int> branch_id { get; set; }
    public string branch_name { get; set; }
    public string branch_code { get; set; }
    public string account_group_1 { get; set; }
    public Nullable<int> is_deleted { get; set; }
    public Nullable<int> user_id { get; set; }
    public string fullname { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public Nullable<System.DateTime> date_submitted { get; set; }
    public Nullable<System.DateTime> deadline { get; set; }
    public Nullable<int> added_by { get; set; }
    public Nullable<int> team_leader { get; set; }
    public string reference { get; set; }
    public Nullable<System.DateTime> viewed_at { get; set; }
}

public partial class vw_visibility_surveys
{
    public int id { get; set; }
    public Nullable<System.DateTime> call_date { get; set; }
    public Nullable<int> branch_id { get; set; }
    public string branch_name { get; set; }
    public string branch_code { get; set; }
    public string account_group_1 { get; set; }
    public Nullable<int> is_deleted { get; set; }
    public Nullable<int> user_id { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public Nullable<System.DateTime> date_submitted { get; set; }
    public Nullable<System.DateTime> deadline { get; set; }
    public Nullable<int> added_by { get; set; }
    public string reference { get; set; }
    public Nullable<System.DateTime> viewed_at { get; set; }
}

public partial class vw_visibility_surveys_tl
{
    public int id { get; set; }
    public Nullable<System.DateTime> call_date { get; set; }
    public Nullable<int> branch_id { get; set; }
    public string branch_name { get; set; }
    public string branch_code { get; set; }
    public string account_group_1 { get; set; }
    public Nullable<int> is_deleted { get; set; }
    public Nullable<int> user_id { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public Nullable<System.DateTime> date_submitted { get; set; }
    public Nullable<System.DateTime> deadline { get; set; }
    public Nullable<int> added_by { get; set; }
    public string reference { get; set; }
    public Nullable<System.DateTime> viewed_at { get; set; }
    public Nullable<int> assigned { get; set; }
    public string fullname { get; set; }
}

public partial class sp_getAssignedUsers_Result
{
    public Nullable<int> id { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string fullname { get; set; }
    public string firstname { get; set; }
    public string middle { get; set; }
    public string lastname { get; set; }
    public string type { get; set; }
    public string area { get; set; }
    public Nullable<double> is_active { get; set; }
    public string email { get; set; }
    public string agency { get; set; }
    public Nullable<int> team_leader { get; set; }
}
