//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<vw_data_workplan_tl> vw_data_workplan_tl { get; set; }
    public virtual DbSet<Data_Workplan> Data_Workplan { get; set; }
    public virtual DbSet<Data_User_Activity_Log> Data_User_Activity_Log { get; set; }
    public virtual DbSet<vw_visibility_surveys_tl> vw_visibility_surveys_tl { get; set; }
    public virtual DbSet<vw_visibility_surveys> vw_visibility_surveys { get; set; }
    public virtual DbSet<Ref_User> Ref_User { get; set; }
    public virtual DbSet<Data_Visibility_Picture> Data_Visibility_Picture { get; set; }

    public virtual int sp_getWorkplansTLViewByUserId(Nullable<int> userId)
    {
        var userIdParameter = userId.HasValue ?
            new ObjectParameter("userId", userId) :
            new ObjectParameter("userId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getWorkplansTLViewByUserId", userIdParameter);
    }

    public virtual ObjectResult<sp_getAssignedUsers_Result> sp_getAssignedUsers(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAssignedUsers_Result>("sp_getAssignedUsers", idParameter);
    }
}
